### ISSUE TITLE
Suggestion: vis_dat() keep type colors constant

### ISSUE THREAD

**Issue by jzadra** [ropensci/visdat#104]
Currently `vis_dat()` uses the default method to assign colors to discrete values for each of the types of data (numeric, character, posix, etc).  However, this means that if a dataset only has numeric, the numeric will be orange.  If it has numeric and character, the character will be orange and the numeric will be blue.

It might be better if these colors were consistent regardless of the number of categories of data in a table.

**Comment by njtierney** [comment]
Hello!

Agreed! This is something I've been thinking about here in #26 - I'm going to close this issue for the moment as I discuss things in more detail over there. Thanks for posting :)
