### ISSUE TITLE
vis_cor(iris[,1:4])  shows plot ok but color LEGEND (@right) only shows red, positive values

### ISSUE THREAD

**Issue by sfd99** [ropensci/visdat#110]
Hi, 
_I love VISDAT!_

  **vis_cor(iris[,1:4])**  
shows plot ok, 
but the correlation color LEGEND (@right of the plot) ,
only shows positive values: 
    0.0 (white)
    0.5 (light red)
    1.0 (dark red)
but the Legend _does not show the negative value:  -0.5 (blue).
The negative (blue) value is missing in the correlation Legend scale.
Try it!.

_OTOH:_
**vis_cor(mtcars)**  or  **vis_cor(airquality)**
 does show the correct LEGEND.
(ie: negative _and_ positive values).

**sfd99
San Francisco**

**Comment by njtierney** [comment]
Here's a minimal reprex:

``` r
library(visdat)

vis_cor(airquality)
```

![](https://i.imgur.com/F2DcbVZ.png)

``` r

vis_cor(iris[, 1:4])
```

![](https://i.imgur.com/ZLz3nuJ.png)

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by njtierney** [comment]
Thanks for posting this issue!

This is now resolved in the dev version, which should be on CRAN this week:

``` r
library(visdat)

vis_cor(airquality)
```

![](https://i.imgur.com/ELoAFi1.png)

``` r

vis_cor(iris[, 1:4])
```

![](https://i.imgur.com/KQfuHz0.png)

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
