### ISSUE TITLE
Use rOpenSci pkgdown template?

### ISSUE THREAD

**Issue by maelle** [ropensci/visdat#115]
:wave: here! Would you be interested in using rOpenSci pkgdown template for your package doco (I've just learnt this word by seeing the latest commit to your pkgdown config :grin: )? See https://ropensci.github.io/rotemplate/ The package and its guidance are brand-new, so comments welcome.

**Comment by njtierney** [comment]
Yes that sounds wonderful!

**Comment by njtierney** [comment]
Although it looks like I don't quite get the changes - the blue banner has dissappeared, but when run locally I got the nice blue banner:

![image](https://user-images.githubusercontent.com/6488485/55044094-15ed6100-508d-11e9-98e8-d5415d3901ad.png)

Any thoughts?

the rotemplate was easy to set up! I've got a few minor suggestions for improving readability of the README in a PR that should be incoming soon.

**Comment by maelle** [comment]
ah weird! do you think it could be due to the doc search? your website is the first one we apply the template to that has doc search so that might be the issue? I'll investigate!

**Comment by maelle** [comment]
Can you try again with the new version of the rotemplate package? I only changed the order of the CSS lines in head.html. It's very puzzling that the website looks different locally, and then online you get no rOpenSci styling at all.

**Comment by maelle** [comment]
Even the favicon disappeared in the online version!

**Comment by maelle** [comment]
changing the order did nothing in my fork :thinking:
