### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [ropensci/visdat#144]
Some topics are missing from the configuration file.

```r
Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: add_vis_dat_pal, all_numeric, compare_print, dat_bin, expect_frame, expect_guide_label, fingerprint, gather_cor, guess_type, label_col_missing_pct, miss_guide_label, scale_01, test_if_dataframe, typical_data, typical_data_large, vis_binary, vis_create_, vis_extract_value_, vis_gather_, vis_value, visdat
```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by maelle** [comment]
@njtierney friendly reminder :smile_cat:

**Comment by maelle** [comment]
@njtierney friendly reminder :smile_cat:

**Comment by maelle** [comment]
@njtierney Happy New Year! Friendly reminder :smile_cat:

**Comment by njtierney** [comment]
Finally getting to this! Apologies for the delay.

Hopefully this is resolved in https://github.com/ropensci/visdat/pull/156

**Comment by njtierney** [comment]
I think this should all be good now, @maelle ? Let me know :)

**Comment by maelle** [comment]
Yes if https://docs.ropensci.org/visdat/reference/index.html looks ok to you! Thanks a lot!
