### ISSUE TITLE
Background of vis_miss() plot is transparent when saving to file

### ISSUE THREAD

**Issue by philsf** [ropensci/visdat#150]
Hi, whenever I try to save a plot from `vis_miss()` to file, the background of the PNG is transparent, which makes it very hard to understand the elements. Attached are a screenshot of what I get and the actual file that was created.

```r
airquality %>% vis_miss()
ggsave("air.png", h = 4, w = 4)
```

Screenshot of how it looks when I open the PNG.
![image](https://user-images.githubusercontent.com/5522672/205717751-7abf4130-5f01-4714-b3d4-cca3eb2dc5ae.png)

The actual PNG file created from `vis_miss()`.
![air](https://user-images.githubusercontent.com/5522672/205717523-0124ef25-00e8-45e5-b95a-b4a6edbd1656.png)

**EDIT** I just found out that this does not happen if I save to a JPG (which I don't normally use). Perhaps this issue is exclusive to the PNG format?

**Comment by njtierney** [comment]
Hi there - yes you are correct! That is an issue with PNG images vs other formats - PNG will add transparency by default, I think there's a way to not do that, but I'm not 100% sure how to do it. All the best!
