### ISSUE TITLE
`gather_()` was deprecated in tidyr 1.2.0.

### ISSUE THREAD

**Issue by arora123** [ropensci/visdat#154]
Calling vis_dat() for any data set produces this warning. 

`gather_()` was deprecated in tidyr 1.2.0.
ℹ Please use `gather()` instead.
ℹ The deprecated feature was likely used in the visdat package.

This might create an error in the future.

---

A deprecated feature being used.

```r
visdat::vis_dat(mtcars)
```

**Comment by njtierney** [comment]
Hi there!

Sorry I need to push the new changes from visdat onto CRAN now, this has been resolved in the latest dev version from GitHub :)

**Comment by arora123** [comment]
Thanks!
