### ISSUE TITLE
visdat::vis_miss uses deprecated function

### ISSUE THREAD

**Issue by ReedMerrill** [ropensci/visdat#155]
`visdat::vis_miss` calls `gather_` from Tidyr, which now produces the following warning message:

```
Warning message:
`gather_()` was deprecated in tidyr 1.2.0.
ℹ Please use `gather()` instead.
```

I can confirm that I am using tidyr >1.2

**Comment by njtierney** [comment]
Hi there! Thanks for posting!

I'm working on submitting a patch for visdat this week, the current development version of visdat from github removes this issue :)

**Comment by njtierney** [comment]
Now resolved
