### ISSUE TITLE
create and add `vis_compare`

### ISSUE THREAD

**Issue by njtierney** [ropensci/visdat#17]
Just a note to myself so I don't forget.

vis_compare would show the difference between two dataframes. It would be very similar to vis_miss, where you basically colouring cells according to "match" and "non-match". The code for this would be pretty crazy simple...maybe

``` r
x <- 1:10

y <- c(1:5, 10:14)

x == y
```

returns 

``` r
 [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE
```

Similar to vis_miss, black could indicate a match, and white a non match.Although, it would be interesting to maybe use another colour.

One of the challenges with this would be cases where the datasets are different dimensions.One option could be to return as a message the columns that are not in the same dataset. Matching rows could be done by row number, and just lopping off the trailing ones and spitting out a note. Then, if the user wants, it could use an ID/key to match by.

**Comment by masalmon** [comment]
So this would be a kind of left_join / any join? 
In a join you have

* The columns you use for joining
* The other columns that are renamed if they have the same name (as in date.x, date.y)

With vis_compare, you'd kind of merge date.x and date.y and visualize their differences? And columns that exist only in one of the initial tables are not interesting so you'd de-select them?

**Comment by njtierney** [comment]
Yup, this is the general gist - visualise only the rows and columns that are present in both.

One idea is for the columns or rows that are not present in both tables/dataframes is to put them as a kind of marginal plot on the rows and columns. But I'm not sure if that would really work.

**Comment by njtierney** [comment]
Just a quick note about matches and antimatches, this might prove useful: https://tonybreyal.wordpress.com/2011/11/29/outersect-the-opposite-of-rs-intersect-function/

**Comment by njtierney** [comment]
I am happy with vis_compare at the moment - the problem with handling datasets that don't have the same dimensions is hard to solve. Here are some options:

1. Spit a warning if the dimensions aren't the same (current behaviour)
1. Take the rows and columns that match (based on a key) - display a warning for which columns/rows that don't match.
2. Take the first $n$ rows and the first $p$ columns that are in the first dataset. Display a warning that this is the behaviour.

Perhaps there could be extra options for these?

**Comment by njtierney** [comment]
Thanks @maelle :) So glad that you like it!

Do you think the options I've given above are needed? I'm looking to close down issues for visdat and the extra options I've given here feel like I'm getting diminishing returns - what do you think?

**Comment by maelle** [comment]
I think it works well now, 2 and 3 are nice to have but not strictly necessary?

**Comment by njtierney** [comment]
OK great!

I'll remove the current warning message and close this issue - I can come back to these points later if I want to spruce things up.

**Comment by njtierney** [comment]
For completeness, here is the current output:

``` r
library(visdat)

iris_diff <- iris
iris_diff[1:10, 1:2] <- NA

# when they are not different
vis_compare(iris, iris)
```

![](https://i.imgur.com/x1ywmaJ.png)

``` r

# when they are different
vis_compare(iris, iris_diff)
```

![](https://i.imgur.com/f1VhQI7.png)

``` r

# when data of different dimensions is fiten
vis_compare(airquality, iris)
#> Error in vis_compare(airquality, iris): Dimensions of df1 and df2 are not the same. vis_compare currently only handles dataframes of identical dimensions.
```

Created on 2018-04-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
