### ISSUE TITLE
write `vis_dat` and `vis_miss` in `plotly` and give them good names

### ISSUE THREAD

**Issue by njtierney** [ropensci/visdat#24]
It's awesome that I can run `vis_dat` and then `ggplotly()`, and get an interactive plot.

But, it's really slow to do that, and from what I understand of plotly, it'll be way quicker if it's written in regular plotly code.

Possible names for these interactive plots?

vis_dat_ly? vis_miss_ly?

Or perhaps I include an "interactive == TRUE" argument inside vis_dat and vis_miss? I think I like this option more.

Any thoughts, @cpsievert ?

**Comment by cpsievert** [comment]
If you think there's any possibility you'll want different arguments for the plotly version, I'd go with a new functions rather than a new argument.

BTW, we have a WebGL heatmap in beta right now. You can't create them from the R package yet, but once that is working, you should be able to render a lot more cells :)

**Comment by njtierney** [comment]
OK sure thing, I think they should get new names then. The question is, what to call them?

Any thoughts on these names?

- `vis_dat_ly`
- `vis_datly`
- `vis_dat_intx`

That's really exciting to hear about WebGL heatmaps! In the interim I think I'll just write them using the plotly code you suggested in the previous issue: https://github.com/njtierney/visdat/issues/2

> It will be less of a hack if you use [`plotly(..., type = "heatmap")`](https://plot.ly/r/reference/#heatmap-hoverinfo). You can control the hover-text via the [hoverinfo property](https://plot.ly/r/reference/#heatmap-hoverinfo)

**Comment by cpsievert** [comment]
I like `vis_datly`

**Comment by njtierney** [comment]
Hok so the current idea is that there will be plotly implementation of all of the visdat funs - they will just end in `_ly`. At the moment only `vis_miss_ly` is implemented in the way that I would like, and it still needs some work. 

The next version of `visdat` should include really nice `plotly` functions that looks similar to the ggplot versions.

**Comment by njtierney** [comment]
This issue is now a duplicate of #36
