### ISSUE TITLE
vis_dat_ly currently doesn't work

### ISSUE THREAD

**Issue by njtierney** [ropensci/visdat#25]
I'm probably not doing a great job of following the instructions from the [plotly site](https://plot.ly/r/heatmaps/), and I haven't used pure plotly syntax that much, and I don’t work with plotting matrices that often, so I'm probably missing something obvious here, but when I try:

``` r
 # apply the fingerprint function to get the class
  d <- x %>% purrr::dmap(fingerprint) %>% as.matrix()

  # heatmap fails due to not being a numeric matrix
  # heatmap(d)

  # plotly fails due to the number of colours being too many?
  plotly::plot_ly(z = d,
                  type = "heatmap")
```

I get the error message

```
Warning messages:
1: In RColorBrewer::brewer.pal(N, "Set2") :
  n too large, allowed maximum for palette Set2 is 8
Returning the palette you asked for with that many colors

2: In `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  :
  duplicated levels in factors are deprecated
```

I get the feeling that I might going to need to convert the classes into numbers, and provide distinct colours for each class, and perhaps a link/dictionary for each class. Or perhaps be a little more descriptive with the axes.

@cpsievert , any chance you could point me in the right direction to fix this?

**Comment by cpsievert** [comment]
Hmm, not sure, could you provide code to produce `x`?

**Comment by njtierney** [comment]
oops, sorry! 

`example2` is the example dataset taken from visdat/csv-fingerprint

```r
library(visdat)
library(dplyr)
library(plotly)

x <- example2

 d <- x %>% purrr::dmap(fingerprint) %>% as.matrix()

  # heatmap fails due to not being a numeric matrix
  # heatmap(d)

  # plotly fails due to the number of colours being too many?
  plotly::plot_ly(z = d,
                  type = "heatmap")
```

**Comment by cpsievert** [comment]
Ack. I might have lead you astray by suggesting a heatmap. The heatmap basically assumes you have a _numeric_ matrix for z (I should be throwing a warning/error for this example). You could do some sort of workaround like this:

```r
library(visdat)
library(plotly)

d <- example2 %>% purrr::dmap(fingerprint) %>% as.matrix()
n <- nrow(example2)

categories <- sort(unique(c(d)))
m <- matrix(match(d, categories), nrow = n)
txt <- matrix(paste(as.matrix(example2), "<br />", d), nrow = n)

plot_ly(
  z = m, x = names(example2), text = txt, hoverinfo = "text", type = "heatmap",
  colorbar = list(ticktext = categories, tickvals = seq_along(categories))
) %>% layout(xaxis = list(title = ""))
```

This sort of works, but the colorbar is awkward. You could easily remove it, and rely on the tooltip to decode the variable types, or hack together a custom legend, but you wouldn't be able to toggle entries.

The `ggplotly()` version looks better because I'm actually drawing 4 different groups of rectangles (whenever the `z` aesthetic in `geom_tile()` is discrete) which is why it's so slow.

```r

l <- plotly_build(vis_dat(example2))
length(l$data)
#> [1] 4
str(l$data[[1]])
#> List of 15
#> $ x          : num [1:15726] 0.5 0.5 1.5 1.5 0.5 NA 0.5 0.5 1.5 1.5 ...
#> $ y          : num [1:15726] 0.5 1.5 1.5 0.5 0.5 NA 1.5 2.5 2.5 1.5 ...
#> $ text       : chr [1:15726] "APN<br>variables: id<br>rows: 1<br>valueType: character" "APN<br>variables: id<br>rows: 1<br>valueType: character" "APN<br>variables: id<br>rows: 1<br>valueType: character" "APN<br>variables: id<br>rows: 1<br>valueType: character" ...
#> $ key        : logi NA
#> $ type       : chr "scatter"
#> $ mode       : chr "lines"
#> $ line       :List of 3
#> ..$ width: num 1.89
#> ..$ color: chr "transparent"
#> ..$ dash : chr "solid"
#> $ fill       : chr "tozerox"
#> $ fillcolor  : chr "rgba(248,118,109,1)"
#> $ name       : chr "character"
#> $ legendgroup: chr "character"
#> $ showlegend : logi TRUE
#> $ xaxis      : chr "x"
#> $ yaxis      : chr "y"
#> $ hoverinfo  : chr "text"
```

**Comment by njtierney** [comment]
Apologies for not getting back to you sooner, @cpsievert !

This workaround is really nice! But as you say, the colourbar is a bit awkward as it doesn't provide distinct sections. I think that the idea of hacking together a custom legend could work well, perhaps we could assign colours to certain R classes and keep this fixed across `vis_dat`?

**Comment by njtierney** [comment]
just occurred to me that it would be a good idea to implement this as `vis_miss_ly`. Although hacking together a legend for classes would be a bit tricky, missing data is more straightforward - only present/missing.

```
library(visdat)
library(plotly)

vis_miss_ly <- function(x){
    
x.na <- is.na(x)
d <- x.na
n <- nrow(x)

categories <- sort(unique(c(d)))
m <- matrix(match(d, categories), nrow = n)
txt <- matrix(paste(as.matrix(x), "<br />", d), nrow = n)

plot_ly(z = m, 
        x = names(x), 
        text = txt, 
        hoverinfo = "text", 
        type = "heatmap",
        colorbar = list(ticktext = categories, 
                        tickvals = seq_along(categories))
) %>% layout(xaxis = list(title = ""))

}

vis_miss_ly(airquality)
```

**Comment by njtierney** [comment]
closing this issue and carrying on in #36 to avoid duplication of issues
