### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by maelle** [ropensci/visdat#80]
Hi @njtierney :wave: 

It seems your Appveyor hook gets failed deliveries. Right now the builds are under your account, although the badge says otherwise (we're still thinking about where to have Appveyor builds, let it stay under your account for now :pray: sorry about the confusion)

* Update the badge when you get a chance

* Contact Appveyor support team about https://github.com/ropensci/visdat/settings/hooks/8349541 They'll want to know info about the latest delivery

    * X-GitHub-Delivery: efbf7510-49ba-11e8-8fe4-9a859c6dce5c

    * Time 2018-04-27 03:33:06

Thanks and again sorry for the confusion as we're currently trying to harmonize and improve our Appveyor strategy 😀

**Comment by maelle** [comment]
I forgot to mention that their email address is team@appveyor.com

**Comment by maelle** [comment]
Maybe try that from Appveyor first

"    If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 

    If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account."

**Comment by njtierney** [comment]
Thanks for this, Maëlle! :)

I haven't had a lot of time to look at visdat lately, I'm hoping to make another release in the next 4-6 weeks, I'll try handle this in the next few weeks.

**Comment by maelle** [comment]
Thanks!

**Comment by njtierney** [comment]
OK great, looking at this now, I think that things are building properly, I went to the appveyor page and asked it to build again and it refrehsed from the one 10 months ago to the most recent commit from 10 months ago

**Comment by njtierney** [comment]
Tests currently running 🤞

**Comment by njtierney** [comment]
OK, tests are good, just updated the README !

**Comment by njtierney** [comment]
Thanks Maëlle!

**Comment by maelle** [comment]
I still see the webhook as broken in settings?

**Comment by njtierney** [comment]
Hmmm, ah, I see this now - sorry I thought that this was more to do with the badge. I actually don't quite understand how this gets failed deliveries, but

> If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically. If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account."

I'm not sure how to really handle this, the webhook URL on the settings page in appveyor is the same as the one on the github one in settings.

Maybe I email the team and give them the latest delivery info, as you suggested initially, or, I can delete the appveyor project and start a new one?

**Comment by maelle** [comment]
Given their impatience with my emails, if you don't care too much about the project history, it's probably  easier to delete and re start the Appveyor project 😢

**Comment by njtierney** [comment]
OK can do :)

**Comment by njtierney** [comment]
OK so I deleted and created a new project, it's building OK: https://ci.appveyor.com/project/njtierney/visdat

But maybe it takes a while for this to update?

**Comment by njtierney** [comment]
Current status: 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/6488485/40945997-a16abee4-689e-11e8-8b48-78a2aad2293f.png">

**Comment by njtierney** [comment]
OK so on my machine I get this: 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/6488485/40950307-942168de-68b5-11e8-8238-34199a18dba6.png">

But that is not reflected on the github site:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/6488485/40950330-a5de7e5e-68b5-11e8-87ac-d94ad61e0b7d.png">

**Comment by maelle** [comment]
I see a green badge 🎉 why are there 2 Appveyor webhooks now? 🙈 both work but one should be enough? Sorry and thanks for your patience.

Reg issue labels, why do you use labels and not milestones for versions btw? ☺

**Comment by njtierney** [comment]
Yay green lights!

hmmm, not sure - let me look into why there are 2 webhooks.

Good question re labels vs milestones - I'm not sure why I use labels! What is the difference between a label and a milestone? :)

**Comment by njtierney** [comment]
OK so removed the extra webhook :)

**Comment by maelle** [comment]
Ok so I think this is solved (and for anyone reading this one day and thinking I'm rude, we discussed milestones elsewhere 😸 ). Thanks for your patience @njtierney!

**Comment by njtierney** [comment]
OK great! Thanks for helping me sort this out and being so helpful, @maelle :)
