### ISSUE TITLE
Example: vis_expect(airquality, ~.x >= 25) shows plot with wrong T/F colors...

### ISSUE THREAD

**Issue by sfd99** [ropensci/visdat#90]
- visdat 0.5.1 (installed f/GitHub)
- R version 3.5.1 RC (2018-06-24 r74934) -- "Feather Spray"
- latest Rstudio version 1.1.453
- Ubuntu Linux 14.04 LTS 32-bits.

The Problem:
==========
In your example code:
 > vis_expect(airquality, ~.x >= 25)
seems to invert the TRUE/FALSE colors in the plot.
> head(airquality)
  Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
5    NA      NA 14.3   56     5   5
6    28      NA 14.9   66     5   6

Yet, the plot of:
  > vis_expect(airquality, ~.x >= 25)
shows exactly the wrong (opposite) T/F colors...

What am I doing wrong?
Love VISDAT! HELP!...
SFd99
confused in San Francisco.

**Comment by njtierney** [comment]
Thanks for filing an issue!

I think that this is a bug, I'll look into this soon and get back to you.

**Comment by sfd99** [comment]
NJ -any news about the fix for this issue?
Have not heard from you in a while...

Thanks for any update 
to this T/F color problem! :-)

**Comment by samanthalazaro** [comment]
Hello,
I think I know where the error may be. In the vis-expect.R scrip, inside the expect_guide_label function:

`else {

    # calculate rounded percentages
    p_expect_false <- round(p_expect, 1)
    p_expect_true <- round(100 - p_expect,1)

    # create the labels
    p_expect_false_lab <- paste("FALSE \n(",
                                p_expect_false,
                                "%)",
                                sep = "")

    p_expect_true_lab <- paste("TRUE \n(",
                               p_expect_true,
                               "%)",
                               sep = "")
  }` 
I tried the code and I think it should be:
```
 p_expect_false_lab <- paste("**TRUE** \n(",
                                p_expect_false,
                                "%)",
                                sep = "")

    p_expect_true_lab <- paste("**FALSE**\n(",
                               p_expect_true,
                               "%)",
                               sep = "")
```

I don't know if this change will cause in any conflict in the code so I'm not making a pull request...
Tell me if it works for you.

**Comment by njtierney** [comment]
Thank you very much @samanthalazaro ! I really appreciate you finding this error! :)
