### ISSUE TITLE
Cohere other `ggplot2` function?

### ISSUE THREAD

**Issue by JiaxiangBU** [ropensci/visdat#99]
I am a new user for `visdat`, which is cool for visualizing data.
And I find the plot produced by `vis_dat` and `vis_miss` seems from `ggplot2`.

But I find add other `ggplot2`  function like `labs` to the obejct of `vis_dat` and `vis_miss`.
Is there a way to cohere `vis_dat` and `vis_miss` with other `ggplot2` function.

**Comment by JiaxiangBU** [comment]
I work it out ...

**Comment by njtierney** [comment]
Hi there!

If you'd like to change the labels using `labs`, you can do the following

``` r
library(visdat)

vis_dat(airquality)
```

![](https://i.imgur.com/MoThuvj.png)

``` r

library(ggplot2)
vis_dat(airquality) + 
  labs(x = "Change the x axis label",
       y = "Change the y axis label")
```

![](https://i.imgur.com/7kPEjch.png)

<sup>Created on 2018-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Let me know if you've got any questions about this, I'm going to close the issue for now.
